### ISSUE TITLE
LC3 tutorial page

### ISSUE THREAD

**Issue by Benjaminkanderson** [Benjaminkanderson/in-to-cm#2]

**Comment by CharlesJones88** [comment]
This URL is a tutorial of multiplication in LC-3
http://www.lc3help.com/tutorials/Multiplication/

**Comment by Benjaminkanderson** [comment]
Nice! :+1:

**Comment by CharlesJones88** [comment]
This URL is shows how to convert C to LC-3 Assembly language
http://www.cs.colostate.edu/~fsieker/misc/CtoLC3.html

**Comment by CharlesJones88** [comment]
Actual c to lc3 converter
http://www.lc3help.com/downloads/c_to_lc3_convertor.zip

**Comment by CharlesJones88** [comment]
Closing issue for this project.
